context("Conditions")
library(karel)

test_that("Checking conditions work fine.", {
  generar_mundo("world_101")
  expect_true(frente_abierto())
  expect_false(frente_cerrado())
  expect_true(izquierda_abierto())
  expect_false(izquierda_cerrado())
  expect_false(derecha_abierto())
  expect_true(derecha_cerrado())
  expect_false(hay_cosos())
  expect_true(no_hay_cosos())
  expect_true(karel_tiene_cosos())
  expect_false(karel_no_tiene_cosos())
  expect_true(mira_al_este())
  expect_false(mira_al_oeste())
  expect_false(mira_al_norte())
  expect_false(mira_al_sur())
})
