message_texts[["en"]] <- list(
  error_general = "You made a mistake before and can't ask Karel to do more things.",
  start_again = "Generate the world again and start all over.",
  cant_move_east = "Karel can't move east, because there's a wall",
  cant_move_west = "Karel can't move west, because there's a wall",
  cant_move_south = "Karel can't move south, because there's a wall",
  cant_move_north = "Karel can't move north, because there's a wall",
  cant_put_beeper = "Karel can't put a beeper since there aren't any left its bag.",
  cant_pick_beeper = "There are no beepers here to pick.",
  world_doesnt_exist = "Required world doesn't exist.",
  do_sth_first_x = "Karel hasn't received any instruction yet.",
  do_sth_first_arrow = "Perform at least one action first and then call run_actions().",
  time_less_than_one_x = "You provided a value for time less than one.",
  time_less_than_one_arrow = "First time available is 1.",
  time_too_big_x = "You provided a value for time too big.",
  time_too_big_arrow = "Latest time available is",
  check_user_world_general = "We are checking that the world you provided is correct.",
  check_user_world_element_missing_x = "is missing in the provided world.",
  check_user_world_try_again = "Please check the world you created and try again.",
  check_user_world_wrong_nx = "nx, the number of avenues, must be numeric of length 1.",
  check_user_world_wrong_ny = "ny, the number of streets, must be numeric of length 1.",
  check_user_world_wrong_karel_x = "\nkarel_x, the x-coordinate for Karel's initial position, must be numeric of length 1, and between 1 and nx.",
  check_user_world_wrong_karel_y = "karel_y, the y-coordinate for Karel's initial position, must be numeric of length 1, and between 1 and ny.",
  check_user_world_wrong_karel_dir = "karel_dir, Karel's initial direction, must be numeric of length 1, either 1, 2, 3 or 4.",
  check_user_world_wrong_beepers_bag = "beepers_bag, the number of beepers in Karel's bag, must be numeric of length 1, greater or equal than zero, including Inf.",
  check_user_world_wrong_beepers_xyn = "beepers_x, beepers_y and beepers_n must be all NULL or numeric vectors of the same length; beepers_x and beepers_y must be between 1 and nx or ny, respectively; and beepers_n must be greater or equal than 1.",
  check_user_world_wrong_walls1 = "must be either NULL of a data.frame.",
  check_user_world_wrong_walls2 = "has 0 rows.",
  check_user_world_wrong_walls3 = "Column",
  check_user_world_wrong_walls4 = "is missing in data.frame",
  check_user_world_wrong_walls5 = "can't have NA values.",
  check_user_world_wrong_walls6 = "must have all numeric columns.",
  check_user_world_wrong_walls7 = "must have all integer values, at least in the math sense, not necessarily of class integer.",
  check_user_world_wrong_walls8 = "must have in column x values between 0 and nx-1",
  check_user_world_wrong_walls9 = "must have in column y values between 0 and ny-1",
  check_user_world_wrong_walls10 = "must have in column lgth values greater or equal to 1.",
  check_user_world_wrong_walls11 = "Some lengths in hor_walls are longer than allowed by nx.",
  check_user_world_wrong_walls12 = "Some lengths in ver_walls are longer than allowed by ny."
)


